CKAN_DATA_TYPES = [
        "CSV",
        "PDF",
        "XLS",
        "XML",
        "JSON",
        "Other",
        "RDF",
        "GIS / Shapefile",
        "HTML text",
        "DOC / TXT",
        "Video / Image",
    ]

CKAN_TYPE_CONVERSION_MAPPING = {
        "XLSX": "XLS",
        "Microsoft Excel": "XLS",
        "KML": "GIS / Shapefile",
        "GeoJSON": "GIS / Shapefile",
        "application/vnd.geo+json": "GIS / Shapefile",
        "ArcGIS GeoServices REST API": "GIS / Shapefile",
        "Esri REST": "GIS / Shapefile",
        "SHP": "GIS / Shapefile",
        "OGC WMS": "GIS / Shapefile",
        "QGIS": "GIS / Shapefile",
        "gml": "GIS / Shapefile",
        "WFS": "GIS / Shapefile",
        "WMS": "GIS / Shapefile",
        "API": "GIS / Shapefile",
        "HTML": "HTML text",
        "HTML page": "HTML text",
        "": "HTML text",
        "TEXT": "DOC / TXT",
        "JPEG": "Video / Image",
        "Api": "JSON",
        "CSV downloads": "CSV",
        "csv file": "CSV",
    }