
ALLEGHENY_COUNTY_MUCKROCK_ID = 126
ALLEGHENY_COUNTY_TOWN_NAMES = [
    "Allegheny County",
    "Allison Park",
    "Bairdford",
    "Bakerstown",
    "Bethel Park",
    "Brackenridge",
    "Braddock",
    "Bradfordwoods",
    "Bridgeville",
    "Buena Vista",
    "Bunola",
    "Carnegie",
    "Cheswick",
    "Clairton",
    "Coraopolis",
    "Coulters",
    "Creighton",
    "Crescent",
    "Cuddy",
    "Curtisville",
    "Dravosburg",
    "Duquesne",
    "East McKeesport",
    "East Pittsburgh",
    "Elizabeth",
    "Gibsonia",
    "Glassport",
    "Glenshaw",
    "Greenock",
    "Harwick",
    "Homestead",
    "Imperial",
    "Indianola",
    "Ingomar",
    "Leetsdale",
    "McKees Rocks",
    "Mckeesport",
    "Monroeville",
    "Morgan",
    "Natrona Heights",
    "North Versailles",
    "Oakdale",
    "Oakmont",
    "Pitcairn",
    "Pittsburgh",
    "Presto",
    "Rural Ridge",
    "Russellton",
    "Sewickley",
    "South Park",
    "Springdale",
    "Sturgeon",
    "Tarentum",
    "Turtle Creek",
    "Verona",
    "Warrendale",
    "West Elizabeth",
    "West Mifflin",
    "Wexford",
    "Wildwood",
    "Wilmerding"
]
TEST_DATABASE_URL = "sqlite:///test_database.db"
TEST_DATABASE_FILENAME = "test_database.db"
