"""Create URLErrorInfo table and URL Error Status

Revision ID: 5a5ca06f36fa
Revises: 9afd8a5633c9
Create Date: 2025-01-13 19:02:43.685209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5ca06f36fa'
down_revision: Union[str, None] = '9afd8a5633c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

url_outcome_enum = postgresql.ENUM(
    'pending',
    'submitted',
    'human_labeling',
    'rejected',
    'duplicate',
    name='url_outcome'
)
url_status = postgresql.ENUM(
    'pending',
    'submitted',
    'human_labeling',
    'rejected',
    'duplicate',
    'error',
    name='url_status'
)


def upgrade() -> None:

    url_status.create(op.get_bind())

    op.alter_column(
        table_name='urls',
        column_name='outcome',
        existing_type=url_outcome_enum,
        type_=url_status,
        postgresql_using='outcome::text::url_status'
    )

    url_outcome_enum.drop(op.get_bind(), checkfirst=True)

    op.create_table('url_error_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url_id', sa.Integer(), nullable=False),
        sa.Column('error', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
        sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_error_info')
    # ### end Alembic commands ###
    url_outcome_enum.create(op.get_bind())

    op.alter_column(
        table_name='urls',
        column_name='outcome',
        existing_type=url_status,
        type_=url_outcome_enum,
        postgresql_using='outcome::text::url_outcome'
    )

    url_status.drop(op.get_bind(), checkfirst=True)
