"""Create HTMLContent and RootURL tables

Revision ID: 9afd8a5633c9
Revises: e27c5f8409a3
Create Date: 2025-01-13 15:11:14.736665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import collector_db
from collector_db.enums import PGEnum

# revision identifiers, used by Alembic.
revision: str = '9afd8a5633c9'
down_revision: Union[str, None] = 'e27c5f8409a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

content_type_enum = PGEnum(
    'Title',
    'Description', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Div',
    name='url_html_content_type'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_urls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('page_title', sa.String(), nullable=False),
        sa.Column('page_description', sa.String(), nullable=True),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=False,
            onupdate=sa.text('now()')
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url', name='uq_root_url_url')
    )
    op.create_table('url_html_content',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url_id', sa.Integer(), nullable=False),
        sa.Column('content_type', content_type_enum, nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url_id', 'content_type', name='uq_url_id_content_type')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_html_content')
    op.drop_table('root_urls')
    content_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
