# This is the docker compose file for creating
#  a local database for testing

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - dbscripts:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=HanviliciousHamiltonHilltops
      - POSTGRES_USER=test_source_collector_user
      - POSTGRES_DB=source_collector_test_db
volumes:
  dbscripts: