name: Test Source Collector App

on: pull_request

jobs:
  container-job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: python:3.11.9

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      GOOGLE_API_KEY: TEST
      GOOGLE_CSE_ID: TEST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/test_automated
          pytest tests/test_alembic
